#+TITLE: SolarSailNavigator (Alpha)
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: author:nil

Plot the course of a spacecraft pushed by the pressure of sunlight.

This is the first release of a solar sail navigation plugin for Kerbal
Space Program (KSP, http://www.kerbalspaceprogram.com). It includes a
solar sail model with animated deployment by Sasquatch Marmalade, and
a force model by Fractal_UK from the KSP Interstellar mod, which works
during time warp. See License.md for the KSP Interstellar open source
license. 

This plugin adds two critical features needed to navigate a sail.

1. Set the sail attitude to a reference frame that rotates with with
   the vessel as it orbits the sun. Specify two angles to point the
   sail plus a duration in days. Add as many angle/angle/days
   maneuvers as you like to make an attitude maneuver schedule. Time
   warp ahead, and the plugin will set the vessel's
   attitude. *WARNING:* Not recommended for planet centered orbits
   yet. The current steering strategy is really geared towards the
   center of gravity and sunlight being the same.
2. Preview the future trajectory and what the final orbit looks like
   in map mode, so you can try to plot a trajectory to a planet or
   other destination. Warp ahead, and watch the sail follow your
   planned trajectory. The preview updates automatically as you change
   the attitude maneuver schedule.

** Usage

*** Building a solar sail spacecraft

In the Vehicle Assembly Building (VAB), look in the "Engines" section
for the "Solar Sail" part. The default orientation of the solar sail
part has the back (night) side of the sail pointing upwards, and the
front (sunlit) side facing down, so plan accordingly. When the sail is
deployed, it can shade the solar panels. You alse need to be able to
point the spacecraft in a variety of different directions to control
where it thrusts. So, put survival solar panels that can get light in
all directions - front, back, sides, up, down. Though, as we'll see
later, this plugin doesn't need power to change attitude and get power
if you run out. But, that's cheating.

You can deploy the sail on the launch pad to see how it will look.

*** Deployment

The sail can be deployed and stowed by right clicking on it. It will
show how much thrust (Newtons) and acceleration (m/s^2) it experiences
from sunlight. Once deployed, a "Sail Controls" window will appear.

*** Attitude control

**** Lock Attitude
There is a "Lock Attitude" toggle button. Clicking this will cause the
attitude maneuver profile to be executed, forcing the sail to the
specified attitude.

**** Start Time
This shows the time that the attitude maneuvers begin in Universal
Time (UT) seconds. Click the "Set to Now" button to reset the start
time to now. Do this if you are starting a new sequence.

**** Reference frame

The sail attitude is controlled relative to a reference frame that
rotates with the vessel as it travels around the sun. It is defined by
the vectors:
- X: from the sun to the sail (radial, "R")
- Y: perpendicular to R, lying in the orbit, in the direction of the
  orbit rotation (tangential, "T")
- Z: perpendicular to the orbit plane (normal, "N")

**** Cone
The "Cone" angle is the angle between the sun and the line
perpendicular to the surface of the sail (sail "normal" vector). As
the sail tilts away from the sun, the reflected light will start
generating thrust perpendicular to the sun-sail line. This is useful
for thrusting with the orbit velocity to sail away from the sun, or
against the velocity to tack closer to the sun. At 0 degrees, the sail
faces directly at the sun. At 90 degrees, the sail is edge on to the
sun, which effectively turns the sail off. This is the rotation about
the Z axis, after the clock angle has been applied.

**** Clock
The "Clock" angle is the rotation around the sun-sail line (X or R in
the RTN frame). It lets you direct the solar force above or below the
orbit plane to change the orbit inclination. If the clock angle is 0
degrees, the cone angle tilts the sail within the orbit plane. At
+/-90 degrees, the cone angle tilts the sail out of the orbit plane.

**** Days
This is the number of days to perform the attitude maneuver. Click +/-
to add/subtract one day, and +10/-10 to add/subtract 10 days.

**** Warp
This is the warp factor to use in the calculations. Click "+" to cycle
through all possible options. *WARNING:* Just leave it at the default
100000, unless you know what you're doing. This works just fine for
now long sun-centered orbits. Lowering this value can make the preview
run way too slow.

**** Color
This shows the color of this attitude maneuver segment on the
trajectory preview in map mode.

**** Add/Remove
The "Add" and "Remove" buttons add or subtract attitude maneuvers to
the sequence. The first maneuver cannot be removed.

**** Final Orbit Color
This shows the color of the final orbit, which is drawn in the preview.

**** Total
Total seconds of the entire attitude maneuver sequence.

*** Preview
The "Show Preview" button makes the plugin calculate and render the
future trajectory in map mode. The trajectory will be recalculate and
drawn whenever you change the angles, durations, or number of
maneuvers. This lets you incrementally change parameters and see the
effect on the trajectory. Once you've built an attitude maneuver
sequence that puts your final orbit where you want to go, increase the
time warp and watch the sail follow your trajectory. It will turn the
sail to 90 degrees and stop sailing once completed.

** Helpful Plugins

*** MechJeb
The Mechanical Jeb plugin (http://mechjeb.com) includes a tool called
"Warp Helper" that helps in executing the attitude maneuver
sequence. In the "Warp to" dropdown, select "Time". In the "Warp for"
field, type in the total duration, with "s" at the end for
seconds. Leave "Lead time" at 0s. Click "Warp" and watch it follow the
trajectory, returning to realtime and 90 degrees at the end.

** Known Problems and Limitations

Also see: TODO.org

*** Lines
Fixed size in game space. Should be fixed screen width like orbit
lines.
*** Warp factor
Really should calculate sensible values without user intervention.
*** Target
Need tools to pick a target and show you how far off the sail's final
orbit is, like the rocket maneuver planning tools in map mode do.
*** Planet centered sailing
Sailing around a planet is very different, because gravity and
sunlight don't come from the same source. The plugin needs some tools
to help lay out planet-centered trajectories for tasks like:
- Sail to escape
- Sail in from escape and capture
- Orbit maneuvers around the planet
*** Smaller time units
Hours, minutes, and seconds for the duration of attitude maneuver
segments. Just need a clean interface that isn't too cluttered.

** Wish List

*** More sail models
One refinement that would make the current sail model more realistic
is to add more triangles to make it curved and billow away from the
sun.

Real sail designs like:
- IKAROS, the first solar sail, currently in orbit between Venus and
  Earth
- LightSail, the Planetary Society's cubesat solar sail, with launches
  in May, 2015 and in 2016
Sail concepts like
- Sunjammer (cancelled NASA solar sail test flight)
- Giant interplanetary sails like the Halley Rendezvous designs
- Ultrasail heliogyro
- Large, ultralight Interstellar Probe sail
- Giant interstellar laser-driven sails

*** Automated navigation
Manually building maneuver sequences can get you pretty close to your
destination. But, because of the near infinite variability of how to
steer a sail along the path to your destination and slow accumulation
of sail thrust, it can be difficult to reach it with any accuracy -
like rendezvous and orbital capture. For the moment, you may want a
secondary propulsion system to close the gap.

Professional solar sailors use numerical optimization algorithms to
calculate sail attitude vs. time for them. Manual sail planning can be
a good start for some algorithms, like gradient methods, which will
bring the sail in tight and accurate.

*** Automatic planetary & sun-centered sailing

There are simpler ways to automate sailing than the automated
navigation. There are steering strategies, for example, to
maximize/minimize the change in orbit elements for doing things like:
- Raising / escape
- Lowering / capture
- Inclination changes
- Precess an orbit
- Circularize / increase eccentricity

*** Realism
Real solar sails have a number of complex limitations that affect how
they sail.

**** Deployment
Real sails are too fragile to stow again after
deployment. Realistically, deployment could be a one time staged
event.

**** Pointing away from the sun
Some sail designs are naturally stable and have trouble pointing all
the way to 90 degrees. Limitations on how far away from the sun a sail
can point make life interesting for sail navigators.

**** Attitude control
Real sails use the torque of sunlight to steer. It would be
interesting exercise to have the sail slow down the time warp and use
special sail steering hardware to change attitude - slowly.
- Steering vanes
- Move the center of mass
- Thin film reflective control devices (used by IKAROS)

Real sails have massive moments of inertia, which make traditional
control by reaction wheels and RCS thrusters difficult.

**** Spinning sails
IKAROS spun to hold the sail flat instead of using structural booms.

**** Imperfect reflection
Real sails don't reflect light like a perfect, flat mirror. They are
curved, with wrinkles, and sail film that absorbs and scatters
light. The direction of thrust on a sail is affected by these
factors. Also, a non-flat sail will still present some area to the sun
at 90 degrees and produce a little thrust.
*** TweakScale

Get this plugin working with the sail to fly larger & smaller
sails by scaling the surface area (square scale change).
*** Make the plugin more generic to work with ion engines etc.
